-- Migration: visitor_reports
-- Weekly (Mon–Sun) and monthly (calendar month) "what visitors want to know"
-- reports, generated by the daily insights job and kept permanently
-- (the raw visitor_insights rows are deleted after ~35 days).
-- Also adds the per-user switch for report emails (default on).

begin;

create table if not exists public.visitor_reports (
  id uuid primary key default gen_random_uuid(),
  profile_user_id uuid not null references public.users(id) on delete cascade,
  period_type text not null check (period_type in ('week', 'month')),
  period_start timestamptz not null,
  period_end timestamptz not null,
  total integer not null default 0,
  report jsonb not null default '{}'::jsonb,
  emailed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (profile_user_id, period_type, period_start)
);

create index if not exists visitor_reports_profile_idx
  on public.visitor_reports (profile_user_id, period_start desc);

-- Server-only table: RLS on and no policies, so only the service role can read/write.
alter table public.visitor_reports enable row level security;

alter table public.users
  add column if not exists report_emails boolean not null default true;

commit;
